services:
  mssql-server:
    container_name: mssql-server
    build:
      context: .
      dockerfile: containerfile
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Password
      - MSSQL_AGENT_ENABLED=True
    volumes:
      - sqlvolume:/var/opt/mssql
    ports:
      - "1433:1433"
    healthcheck:
      test: CMD-SHELL /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -Q "SELECT 1" || exit 1
      interval: 90s
      timeout: 10s
      retries: 3


volumes:
  sqlvolume:
