FROM mcr.microsoft.com/mssql/server:2022-latest


# Switch to root user to install Full-Text Search
USER root

# Update the container's package list
RUN apt-get update

# Install the curl package
RUN apt-get install -y curl


# Download the public key 
RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc

# Add the SQL Server 2022 repository
RUN curl -fsSL https://packages.microsoft.com/config/ubuntu/22.04/mssql-server-2022.list | tee /etc/apt/sources.list.d/mssql-server-2022.list

# Install Full-Text Search (FTS) and clean up
RUN apt-get update
RUN apt-get install -y mssql-server-fts


# Expose the default SQL Server port
EXPOSE 1433

CMD [ "/opt/mssql/bin/sqlservr" ]