
version: '3.8'

services:
  azp-agent:
    image: ghcr.io/dotkube/self-hosted-azp-agent:almalinux-9.5-minimal
    container_name: azp-agent-linux
    build: .
    env_file:
      - path: ./.env
        required: true
    restart: unless-stopped
    privileged: true